global_frame: /map
robot_base_frame: base_footprint
update_frequency: 
publish_frequency: 1.0

#publish_voxel_map: true
#
#map_type: voxel
#origin_z: 0.1
#z_resolution: 0.2
#z_voxels: 5
#unknown_threshold: 10
#mark_threshold: 0

obstacle_range: 2.5
raytrace_range: 3.0
inflation_radius: 0.8
observation_sources: scan kinect_scan
scan: {data_type: LaserScan, topic: scan_filtered, marking: true, clearing: true}
kinect_scan: {data_type: LaserScan, topic: nav_kinect/scan_filtered, marking: true, clearing: true}
kinect_cloud: {data_type: PointCloud2, topic: nav_kinect/depth_registered/points, marking: true, clearing: true}
